### PR TITLE
Add OpenJDK 17 images to OpenShift ImageStream templates.

### LINKED ISSUE #243: Add OpenJDK 17 images to OpenShift ImageStream templates
We need to add entries for OpenJDK 17 to the following template files in templates/:
```
"community-image-streams.json"
"image-streams-aarch64.json"
"image-streams.json"
"image-streams-ppc64le.json"
"image-streams-s390x.json"
"openjdk-web-basic-s2i.json"
"openjdk-web-basic-s2i.json.orig"
"runtime-image-streams.json"
```
These changes need to target the `release` branch, in order for the scripts in https://github.com/openshift/library to pull in the changes.
The changed files can be tested by
1. syntax checking by running through a tool like `jq`,
2. importing them into an OpenShift cluster,
3. running the `make import`, `make verify` steps from a clone of https://github.com/openshift/library which has been adjusted to pull the templates from a development fork/branch.

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes and provide comments?

### CODE REVIEW

**Comment by jmtd** [comment]
The PR needs to target the `release` branch, or, it needs to bring the `develop` branch to the same state as the `release` branch for the “templates” directory before adding the JDK17 stuff. We could then merge it and update OpenShift/library to pull from develop instead of release.

**Comment by jhuttana** [comment]
> The PR needs to target the `release` branch, or, it needs to bring the `develop` branch to the same state as the `release` branch for the “templates” directory before adding the JDK17 stuff. We could then merge it and update OpenShift/library to pull from develop instead of release.

On release branch I don't see JDK17 related descriptor file(Which is necessary to do a build to check whether the changes are fine).  I assume things will first go to 'develop' and then to 'release' branch. If that is the case then 'develop' branch should be having whatever 'release' branch has. Please correct me if my understanding is wrong.

**Comment by jhuttana** [comment]
> > The PR needs to target the `release` branch, or, it needs to bring the `develop` branch to the same state as the `release` branch for the “templates” directory before adding the JDK17 stuff. We could then merge it and update OpenShift/library to pull from develop instead of release.
> 
> On release branch I don't see JDK17 related descriptor file(Which is necessary to do a build to check whether the changes are fine). I assume things will first go to 'develop' and then to 'release' branch. If that is the case then 'develop' branch should be having whatever 'release' branch has. Please correct me if my understanding is wrong.


One more time I went through your description in the reported issue and you have already mentioned there about how the changes can be tested :) Sorry I missed that part when I read for the first time:(
But still my confusion about why are we directly branching from 'release' branch and want to do these changes?

**Comment by jhuttana** [comment]
Created another PR by targeting the 'release' branch. So closing this one.

**Pull request closed without merging**
