### PR TITLE
CLOUD-2070 fix access to hsperfdata_jboss

### PR DESCRIPTION
**Pull request by bdecoste**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by rcernich — DISMISSED** [review]

**Review by rcernich — APPROVED** [review]

**Comment by rcernich** [comment]
rebased and merged

**Comment by jmtd** [comment]
This breaks building this image, so I will probably have to revert it.

**Comment by jmtd** [comment]
In case you are curious:

```
Step 24 : RUN bash -x /tmp/scripts/openshift-layer/configure_layers.sh
 ---> Running in 76a809c2d161
+ set -e
++ dirname /tmp/scripts/openshift-layer/configure_layers.sh
+ SCRIPT_DIR=/tmp/scripts/openshift-layer
+ ADDED_DIR=/tmp/scripts/openshift-layer/added
+ MODULES=()
+ OPENSHIFT_LAYER_PATH=/modules/system/layers/openshift
+ OVERLAYS_PATH=/modules/system/layers/base/.overlays
+ MODULES_SOURCE_PATHS=("$JBOSS_HOME/modules/system/layers/base")
+ '[' -f /modules/system/layers/base/.overlays/.overlays ']'
++ find /modules/system/layers/openshift -name module.xml
find: '/modules/system/layers/openshift': No such file or directory
+ cp -p /tmp/scripts/openshift-layer/added/modules/layers.conf /modules/
cp: cannot create regular file '/modules/': Not a directory
```

**Comment by jmtd** [comment]
Link to jira for convenience https://issues.jboss.org/browse/CLOUD-2070

**Pull request closed without merging**
