### PR TITLE
add overrides.yaml and update README (#48)

### PR DESCRIPTION
**Pull request by vorburger**
see #48

### CODE REVIEW

**Comment by jmtd** [comment]
`overrides.yaml` should be renamed e.g. `artefact-overrides.yaml` to distinguish it from the other overrides YAML files. All of the overrides files should probably be documented (but that is not a blocker for this PR)

Putting this in these image sources here would be a short-term solution, because the problem is really over in [cct_modules](https://github.com/jboss-openshift/cct_module), where the artefact definitions are (e.g. https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/jolokia/bash/module.yaml), as @rcernich says in #48 , we probably need community variants of the modules that are pulled in by this image, with correct checksums for the community versions.

**Comment by vorburger** [comment]
> `overrides.yaml` should be renamed e.g. `artefact-overrides.yaml`

done - better?

> Putting this in these image sources here would be a short-term solution

may I open a new issue re. the long-term solution, so that this doesn't hold up merging this PR? #67

**Comment by jmtd** [comment]
This is still an issue for the default `cekit build podman`, in fact any RHEL7-based image, since the prometheus and jolokia artefacts need to be in the cekit cache to build

```
CekitError: ("Error copying resource: 'jmx_prometheus_javaagent'. See logs for more info.", CekitError('Artifact jmx_prometheus_javaagent could not be found',))
```

The issue is gradually going away, the RHEL8 ones should build fine now (RPM-based artefacts), and if we get rid of Jolokia that only leaves Prometheus as the problem for the legacy images.

Perhaps image.yaml should be a RHEL8-based container, not a legacy one.

**Comment by jmtd** [comment]
I'm closing this because the default images don't have the problem this addresses (RHEL8-based) and the RHEL7 ones are getting gradually less and less attention as they are effectively deprecated. I think the thrust of what this is trying to achieve is done (default images build fine in non-special environments) and that gets regularly exercised by GitHub CI too. Thanks for the work!

**Pull request closed without merging**
