### PR TITLE
Openjdk 2427 rsync preserve ubi8

### PR DESCRIPTION
**Pull request by jmtd**
https://issues.redhat.com/browse/OPENJDK-2427

This is the UBI8 port of #411.

 * <s>It is based upon #443 which I needed to build JDK17.</s> _no longer_
 * <s>In the UBI9 version, the test was in `tests/features/java/java_s2i.feature` but we have subsequently marked the whole file `@ignore` due to GHA issues; for that reason, I've put the test into the not-ignored `tests/features/java/java_s2i_inc.feature` here. We'll see if it passes on GHA. It does locally.</s> _no longer_

### CODE REVIEW

**Comment by jerboaa** [comment]
Tests fail for `mtime`:

```
Scenario: Ensure mtime is preserved for build artifacts (OPENJDK-2427) 
```

That's a bit worrying.

**Comment by jmtd** [comment]
I'm afraid I think this is a symptom of the reliability problems we are having for S2I tests on GHA (that I am trying to resolve in #423 ). The smoking gun in the logs:

> 2024-02-13T11:50:21.3822744Z       docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.22/containers/f101ee70de307905f6db69746a2e3b1c8b69bcb87cc6d6e7d3f4993cb1ec67e5/exec: Conflict ("Container f101ee70de307905f6db69746a2e3b1c8b69bcb87cc6d6e7d3f4993cb1ec67e5 is not running")

I'll move the test back to `java_s2i.feature` which means it will be tagged `@ignore` and not run on GHA for the time being.

It passes for me locally.

**Review by sefroberg — APPROVED** [review]
LGTM

**Review by jerboaa — APPROVED** [review]
OK, though I dislike the test situation...

**Pull request merged**
