### PR TITLE
Added LANG environment variable to ubi8-based images.

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes?

### CODE REVIEW

**Comment by jhuttana** [comment]
```
$ podman run --rm -ti localhost/ubi8/openjdk-8-runtime bash
[jboss@4705f0666522 ~]$ echo $LANG
LANG=C.utf8
```

**Review by jerboaa — COMMENTED** [review]
Please add a behave test which asserts that `java -XshowSettings:properties -version 2>&1 | grep file.encoding` has value `file.encoding = UTF-8` when run with those images. Add them for example here: https://github.com/jboss-container-images/openjdk/blob/develop/tests/features/java/openjdk.feature. Adding a test for the LANG variable would be useful too.

**Comment by jhuttana** [comment]
> Please add a behave test which asserts that `java -XshowSettings:properties -version 2>&1 | grep file.encoding` has value `file.encoding = UTF-8` when run with those images. Add them for example here: https://github.com/jboss-container-images/openjdk/blob/develop/tests/features/java/openjdk.feature. Adding a test for the LANG variable would be useful too.


Added behave test and manually tested as below:

Ex:
```
$ podman run --rm -ti localhost/ubi8/openjdk-17-runtime bash -c "java -XshowSettings:properties -version 2>&1 | grep "file.encoding""
 file.encoding = UTF-8
```

**Comment by jhuttana** [comment]
The special character pipe "|"  in behave test action table was throwing "Malformed Table" error.
So I just used `bash -c "$JAVA_HOME/bin/java -XshowSettings:properties -version"` instead of `bash -c "$JAVA_HOME/bin/java -XshowSettings:properties -version 2>&1 | grep file.encoding"`

**Review by jmtd — APPROVED** [review]
LGTM!

**Pull request merged**
