### PR TITLE
Community first!

### PR DESCRIPTION
**Pull request by goldmann**
What $SUBJECT says. Now, by default we build the community image, product version is built by applying the `product-overrides.yaml` file.

### CODE REVIEW

**Comment by goldmann** [comment]
FYI @rcernich

**Comment by goldmann** [comment]
@rcernich as per our chat, I'll go ahead and merge it.

**Comment by rcernich** [comment]
Only comment, instead of `product-overrides.yaml`, did we want to use `rhel7-overrides.yaml`, with an eventual `rhel8-overrides.yaml` when the time comes?  I suspect we'll need to support both rhel7 and rhel8.

**Comment by rcernich** [comment]
oh, one more, please update the readme with the new build instructions for community/product.

**Comment by goldmann** [comment]
It was updated in subsequent commit, see the `openjdk18-dev` branch directly.

**Pull request merged**
