### PR TITLE
Incorporated changes for OpenJ9 due to the update of OpenJDK RHEL8 images

### PR DESCRIPTION
**Pull request by mdrafiur**
…ages

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by jmtd — APPROVED** [review]
LGTM!

**Comment by mdrafiur** [comment]
@jerboaa As you suggested earlier, requesting to merge this PR down to 'release' branch as it has been integrated.

**Comment by jerboaa** [comment]
@mdrafiur @jmtd is doing the merge down usually. So I'd prefer for him to do it. @jmtd OK?

**Comment by jmtd** [comment]
No prob

**Pull request merged**
