### PR TITLE
Move GHA runners to ubuntu-22.04

### PR DESCRIPTION
**Pull request by jmtd**
This is a blind change, I don't know whether further work will be needed to update the actions for Ubuntu 22.04. Hopefully the runs for this PR will shed some light.

### CODE REVIEW

**Comment by jmtd** [comment]
Summarizing current GHA failures in this PR:
* ubi9/openjdk-17 failing due to ubuntu mirror error. This is a transient but frequent problem in this PR.
* ubi9/openjdk-17-runtime due to #353 (ignore in this PR)
* ubi9/openjdk-11: features/image/java/openjdk_s2i.feature:5  Check java perf dir owned by jboss (CLOUD-2070)
    * unrelated, broke by #306 , fixed in #354

**Comment by jmtd** [comment]
I think this is ready for review. There's still a transient Ubuntu mirror issue that we might be able to side-step somehow but I think this is more reliable than the current deprecated runner image despite that.

**Comment by jerboaa** [comment]
@jmtd Could you please force push so as to trigger a new GHA build, please? Hopefully that would give us clean runs.

**Comment by jmtd** [comment]
@jerboaa: 
> Could you please force push so as to trigger a new GHA build, please? Hopefully that would give us clean runs.

Done (and it did! :))

**Review by jerboaa — COMMENTED** [review]
Ship it!

**Comment by jerboaa** [comment]
We'll need something similar for ubi8 as well. Thanks!

**Pull request merged**
