### PR TITLE
[#314] Remove maven.repository.redhat.com/techpreview/all from jboss-settings.xml

### LINKED ISSUE #314: Remove Red Hat tech preview Maven repo from shipped settings.xml
https://github.com/jboss-container-images/openjdk/blob/develop/modules/maven/default/artifacts/opt/jboss/container/maven/default/jboss-settings.xml lists https://maven.repository.redhat.com/techpreview/all in its `repositories` & `pluginRepositories`.
This Maven repository is no longer active and returns 404.

We can safely remove it from the maven settings.

### PR DESCRIPTION
**Pull request by jmesnil**
This fixes #314

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
should I create an `OPENJDK` issue tracker for this change or is #314 enough?

**Comment by jmesnil** [comment]
I don't think the failures are related to the PR. The behave test that fails is

> Check that certain non-UBI packages are not installed

which is unrelated to the removal of the techpreview Maven repo

**Comment by jmtd** [comment]
Filed https://issues.redhat.com/browse/OPENJDK-917 to track this too

**Comment by jmtd** [comment]
The test failures for OpenJDK 11 and 17 S2I are unrelated to this change. They're reporting

    2022-07-27 12:21:30,408 - root - INFO - Message 'dejavu-sans-mono-fonts' was found in the logs

which will need separate investigation.

**Review by jmtd — APPROVED** [review]
LGTM!

**Pull request merged**
