### PR TITLE
CLOUD-2293 add support for building a community based image

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by goldmann** [comment]
I think this one should be dropped since we already added support for community images as part of https://github.com/jboss-container-images/redhat-openjdk-18-openshift-image/pull/32 and other commits that followed after.

**Comment by jorgemoralespou** [comment]
@goldmann where are the community images published?

**Comment by goldmann** [comment]
@jorgemoralespou It was not published yet. I expect to have details at the end of this sprint (2 weeks time frame). We need to figure out a few things before we can push it and release.

**Comment by cmoulliard** [comment]
> we can push it and release

Where such info will be then published (mailing list, ...) as it interests several projects/products ?

**Comment by goldmann** [comment]
Let's track development and outcome in https://issues.jboss.org/browse/CLOUD-2293.

**Pull request closed without merging**
