### PR TITLE
update image streams for December image releases

### PR DESCRIPTION
**Pull request by jmtd**
This can be merged before the images are released (to the develop branch) and we'll need a subsequent merge-down PR for develop→release.

### CODE REVIEW

**Comment by jerboaa** [comment]
Can you explain why the version bump? Has something significantly changed?

**Comment by jmtd** [comment]
> Can you explain why the version bump? Has something significantly changed?

For RHEL8-based images, it's the move from RHEL 8.0 → 8.1.

For OpenJDK 8 / RHEL7, it's due to correcting a labelling issue that's referenced in 
74691b006a84764f7c685085a5eb7fa6ddc2e2b6, although I'm struggling to find the commit that fixed the label.

**Comment by jmtd** [comment]
Ah here we are https://github.com/jboss-container-images/openjdk/pull/99/commits/1deb16a1d9645b933e78736a71deb8e1a0144c20#diff-e4431b64320981a62265702b4291bd37L17

I think I was concerned about CI/CD systems building against the prior version and blocking a respin.

**Review by jerboaa — APPROVED** [review]
This should be fine. I do still wonder if anyone is actually relying on a specific image version, though. I.e. is this something we need to continue doing?

**Comment by yselkowitz** [comment]
Can this be cherry-picked into `ocp-v4.4.0`?

**Pull request merged**
