### PR TITLE
Lower the default MaxRAMPercentage for Maven JVMs

### PR DESCRIPTION
**Pull request by jmtd**
https://issues.redhat.com/browse/OPENJDK-559

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Why not just use this?

```
diff --git a/modules/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh b/modules/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh
index aa67178..a8ae49b 100644
--- a/modules/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh
+++ b/modules/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh
@@ -41,7 +41,7 @@ function maven_init_var_MAVEN_SETTINGS_XML() {
 }
 
 function maven_init_var_MAVEN_OPTS() {
-  export MAVEN_OPTS="${MAVEN_OPTS:-$(${JBOSS_CONTAINER_JAVA_JVM_MODULE}/java-default-options)}"
+  export MAVEN_OPTS="${MAVEN_OPTS:-$(${JBOSS_CONTAINER_JAVA_JVM_MODULE}/java-default-options) -XX:MaxRAMPercentage=25.0}"
 }
 
 function maven_init_var_MAVEN_ARGS() {
```

AFAIK, the last value wins:

```
$ java -XX:MaxRAMPercentage=80.0 -XX:MaxRAMPercentage=25.0 -XX:+PrintFlagsFinal -version 2>&1 | grep MaxRAMPercentage
   double MaxRAMPercentage                         = 25.000000                                 {product} {command line}
```

**Comment by jmtd** [comment]
@jerboaa 
> AFAIK, the last value wins:

In which case that's the approach to take. Thanks! I've updated this PR to implement that.

**Review by jerboaa — CHANGES_REQUESTED** [review]
The test seems to be failing for runtime images. Which makes sense. It should only run for full JDK images.

**Review by jerboaa — APPROVED** [review]
LGTM, provided the tests look sane now.

**Pull request merged**
