### PR TITLE
Updated container metadata for documentation to point at new docs.

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes?

### CODE REVIEW

**Comment by jmtd** [comment]
Thanks - for the builder images that's perfect. For the runtime images, it's not appropriate (documents s2i features they don't have). However, the old value is also problematic! Can we delete the "usage" label from the runtime images for now?

**Comment by jhuttana** [comment]
> Thanks - for the builder images that's perfect. For the runtime images, it's not appropriate (documents s2i features they don't have). However, the old value is also problematic! Can we delete the "usage" label from the runtime images for now?

Sure will do that

**Comment by jhuttana** [comment]
Deleted in-appropriate metadata from runtime descriptors.

**Review by jmtd — APPROVED** [review]
👍🏼

**Pull request merged**
