### PR TITLE
[OPENJDK-2177]Create a dummy module.yaml to move openjdk.feature behave test to mod…

### PR DESCRIPTION
**Pull request by jhuttana**
JIRA: https://issues.redhat.com/browse/OPENJDK-2177
To move openjdk.features behave test, there was need to create dummy module.yaml and a module/jdk/tests/features/ .
Checked the changes locally and the cekit is picking the tests.

### CODE REVIEW

**Comment by jmtd** [comment]
Unfortunately this is not doing what we want, yet. Before, there are 6 Features collected for JDK17 runtime, including Scenario: Check that only OpenJDK 17 is installed; in this PR, that Feature and its Scenarios are not being run.

**Comment by jmtd** [comment]
What's odd is the module (and the tests within it) do seem to be collected by cekit!

**Comment by jhuttana** [comment]
> Check that only OpenJDK 17 is installed

I tried to run that particular scenario locally which gets struck without coming out with some output then  I manually to tried to stop it showed up the output:
```
$ git branch -v
  jlink-dev     6b632d0 Merge pull request #426 from jmtd/jlink-dev-readme
* re-org-tests1 34bfc9c Create a dummy module.yaml to move openjdk.feature behave test to module/jdk/
  ubi8          3c8da9c Merge pull request #427 from jmtd/OPENJDK-2587-tzdata-ubi8
  ubi9          45ab242 Merge pull request #429 from jhuttana/re-org-tests

$ ls -l modules/jdk/tests/features/openjdk.feature 
-rw-r--r--. 1 jhuttana jhuttana 3829 Jan 23 23:22 modules/jdk/tests/features/openjdk.feature

$ cekit --descriptor ubi9-openjdk-17.yaml test  behave --name "Check that only OpenJDK 17 is installed"
2024-01-23 23:23:50,686 tools.py:458        INFO  You are running on known platform: Fedora Linux 38 (Workstation Edition)
2024-01-23 23:23:50,687 base.py:108        INFO  Initializing image descriptor...
2024-01-23 23:23:50,692 resource.py:177        WARNING No value found for 'name' in '{"dest": "/tmp/artifacts/", "path": "modules"}' artifact; using auto-generated value of 'modules'
2024-01-23 23:23:50,694 resource.py:231        INFO  Copying resource 'modules'...
2024-01-23 23:23:50,805 base.py:376        INFO  Rendering Dockerfile...
2024-01-23 23:23:50,848 base.py:422        INFO  Rendering help.md page from template /usr/lib/python3.11/site-packages/cekit/generator/../templates/help.jinja
2024-01-23 23:23:50,864 collector.py:44         INFO  Fetching common steps from 'https://github.com/cekit/behave-test-steps.git'.
Cloning into '/home/jhuttana/workarea/Containers/openjdk/target/test'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 1), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (17/17), 14.43 KiB | 75.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
2024-01-23 23:23:53,749 collector.py:77         INFO  Collecting finished!
USING RUNNER: behave.runner:Runner
Feature: Tests for all openshift images # features/image/openshift.feature:1

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift OpenJDK-only S2I tests # features/image/java/openjdk_s2i.feature:5

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift OpenJDK port tests # features/image/java/ports.feature:4

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift OpenJDK Runtime tests # features/image/java/runtime.feature:4

@ubi9
Feature: Openshift OpenJDK GC tests # features/jboss.container.java.jvm/gc.feature:2

Feature: OPENJDK-559 JVM Memory tests # features/jboss.container.java.jvm/memory.feature:1

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift S2I tests # features/jboss.container.java.run/java.security.feature:4

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift OpenJDK S2I tests # features/jboss.container.maven.s2i/java_s2i_inc.feature:4

Feature: Miscellaneous OpenJDK-related unit tests # features/jboss.container.openjdk/openjdk.feature:1

  @ubi9/openjdk-17 @ubi9/openjdk-17-runtime
  Scenario: Check that only OpenJDK 17 is installed            # features/jboss.container.openjdk/openjdk.feature:15
    When container is started with args                        # steps/container_steps.py:86
      When container is started with args                        # steps/container_steps.py:86 372.489s
      | arg     | value   |
      | command | rpm -qa |
    Then available container log should not contain java-1.8.0 # steps/container_steps.py:61 0.008s
    Then available container log should not contain java-11    # steps/container_steps.py:61 0.006s
    Then available container log should not contain java-21    # steps/container_steps.py:61 0.002s
2024-01-23 23:30:06,445 container.py:100        INFO  Removing container 'b608867d659163752672a9cf8db37b3f34a2bdb01a276b0eeb53fa5e6a047afa', 1 try...
2024-01-23 23:30:06,468 container.py:103        INFO  Container 'b608867d659163752672a9cf8db37b3f34a2bdb01a276b0eeb53fa5e6a047afa' removed

@ubi9/openjdk-11 @ubi9/openjdk-17 @ubi9/openjdk-21
Feature: Openshift S2I tests # features/jboss.container.s2i.core/s2i-core.feature:4

Feature: Miscellaneous general settings unit tests # features/jboss.container.user/general.feature:1

1 feature passed, 0 failed, 11 skipped
1 scenario passed, 0 failed, 64 skipped
4 steps passed, 0 failed, 184 skipped, 0 undefined
Took 6m12.505s
2024-01-23 23:30:06,469 cli.py:503        INFO  Finished!
```
So this means that the cekit is able to pickup the Scenario that is mentioned from the expected path.
But I am not sure why is it not picked in GHA.

**Comment by jhuttana** [comment]
Further, I tried running all the tests and verified that the modules/jdk/tests/features/openjdk.feature are picked.

```
$ git branch -v
  jlink-dev     6b632d0 Merge pull request #426 from jmtd/jlink-dev-readme
* re-org-tests1 34bfc9c Create a dummy module.yaml to move openjdk.feature behave test to module/jdk/
  ubi8          3c8da9c Merge pull request #427 from jmtd/OPENJDK-2587-tzdata-ubi8
  ubi9          45ab242 Merge pull request #429 from jhuttana/re-org-tests

$ ls -l modules/jdk/tests/features/openjdk.feature 
-rw-r--r--. 1 jhuttana jhuttana 3829 Jan 23 23:22 modules/jdk/tests/features/openjdk.feature

$ cekit --descriptor ubi9-openjdk-17.yaml test  behave
.
.
.
Feature: Miscellaneous OpenJDK-related unit tests # features/jboss.container.openjdk/openjdk.feature:1

  @ubi9/openjdk-17 @ubi9/openjdk-17-runtime
  Scenario: Check that only OpenJDK 17 is installed            # features/jboss.container.openjdk/openjdk.feature:15
      When container is started with args                        # steps/container_steps.py:86 34.060s
      | arg     | value   |
      | command | rpm -qa |
    Then available container log should not contain java-1.8.0 # steps/container_steps.py:61 0.005s
    Then available container log should not contain java-11    # steps/container_steps.py:61 0.004s
    Then available container log should not contain java-21    # steps/container_steps.py:61 0.003s
2024-01-24 00:41:51,094 container.py:100        INFO  Removing container '99d30682e5becfa970c74520c986065404f6b488fe9ab6034c0f22fe84d8d1fd', 1 try...
2024-01-24 00:41:51,118 container.py:103        INFO  Container '99d30682e5becfa970c74520c986065404f6b488fe9ab6034c0f22fe84d8d1fd' removed

  @ubi9
  Scenario: Ensure JAVA_HOME is defined and contains Java                   # features/jboss.container.openjdk/openjdk.feature:34
    When container is started with args                                     # steps/container_steps.py:86 10.357s
      | arg     | value                                  |
      | command | bash -c "$JAVA_HOME/bin/java -version" |
    Then available container log should contain OpenJDK Runtime Environment # steps/container_steps.py:50
    Then available container log should contain OpenJDK Runtime Environment # steps/container_steps.py:50 0.004she logs
2024-01-24 00:42:01,483 container.py:100        INFO  Removing container '6b454aa74e52a42e8531df0ef21d7033c26a43d6780fc7a1655bbec3b26fcc2e', 1 try...
2024-01-24 00:42:01,508 container.py:103        INFO  Container '6b454aa74e52a42e8531df0ef21d7033c26a43d6780fc7a1655bbec3b26fcc2e' removed

  @ubi9
  Scenario: Check that certain non-UBI packages are not installed              # features/jboss.container.openjdk/openjdk.feature:41
      When container is started with args                                        # steps/container_steps.py:86 23.816s
      | arg     | value   |
      | command | rpm -qa |
    Then available container log should not contain grub                       # steps/container_steps.py:61 0.008s
    Then available container log should not contain os-prober                  # steps/container_steps.py:61 0.006s
    Then available container log should not contain rpm-plugin-systemd-inhibit # steps/container_steps.py:61 0.005s
2024-01-24 00:42:25,348 container.py:100        INFO  Removing container '5c1c4ef6a2495d2e3d8da3a45372a2d1f4e1aab247bb7fc86d80275640f8420d', 1 try...
2024-01-24 00:42:25,372 container.py:103        INFO  Container '5c1c4ef6a2495d2e3d8da3a45372a2d1f4e1aab247bb7fc86d80275640f8420d' removed

  @ubi9/openjdk-17 @ubi9/openjdk-17-runtime
  Scenario: Check that directories from other JDKs are not present (JDK17)  # features/jboss.container.openjdk/openjdk.feature:61
    When container is started with args                                     # steps/container_steps.py:86 10.553s
      | arg     | value              |
      | command | ls -1 /usr/lib/jvm |
    Then available container log should not contain java-1.8.0              # steps/container_steps.py:61 0.006s
    Then available container log should not contain java-11                 # steps/container_steps.py:61 0.005s
    Then available container log should not contain java-21                 # steps/container_steps.py:61 0.005s
2024-01-24 00:42:35,947 container.py:100        INFO  Removing container 'a9ebef46dad1d78f7c223b6659769c6717168ede30e466cf4ec0aad956cfb306', 1 try...
2024-01-24 00:42:35,970 container.py:103        INFO  Container 'a9ebef46dad1d78f7c223b6659769c6717168ede30e466cf4ec0aad956cfb306' removed

  @ubi9
  Scenario: Ensure LANG is defined and contains UTF-8                 # features/jboss.container.openjdk/openjdk.feature:80
    When container is started with args                               # steps/container_steps.py:86 10.390s
      | arg     | value                                                            |
      | command | bash -c "$JAVA_HOME/bin/java -XshowSettings:properties -version" |
    Then available container log should contain file.encoding = UTF-8 # steps/container_steps.py:50
    Then available container log should contain file.encoding = UTF-8 # steps/container_steps.py:50 0.007she logs
2024-01-24 00:42:46,376 container.py:100        INFO  Removing container '24d7d6be00c31200d32773a22d9ecc92d5a066f3293437581904fafe6b9a356d', 1 try...
2024-01-24 00:42:46,402 container.py:103        INFO  Container '24d7d6be00c31200d32773a22d9ecc92d5a066f3293437581904fafe6b9a356d' removed

  @ubi9
  Scenario: Ensure tar is installed (OPENJDK-1165)                    # features/jboss.container.openjdk/openjdk.feature:87
    When container is started with args                               # steps/container_steps.py:86 10.547s
      | arg     | value |
      | command | tar   |
    Then available container log should not contain command not found # steps/container_steps.py:61 0.006s
2024-01-24 00:42:56,966 container.py:100        INFO  Removing container '6a5cf068630378a482365f15139db7a38d3c48c4facb2753188aa1861e4c489e', 1 try...
2024-01-24 00:42:56,990 container.py:103        INFO  Container '6a5cf068630378a482365f15139db7a38d3c48c4facb2753188aa1861e4c489e' removed

  @ubi9
  Scenario: Ensure tzdata RPM is properly installed (OPENJDK-2519)  # features/jboss.container.openjdk/openjdk.feature:94
      When container is started with args                             # steps/container_steps.py:86 116.229s
      | arg     | value         |
      | command | rpm -V tzdata |
    Then available container log should not contain missing         # steps/container_steps.py:61 0.006s
2024-01-24 00:44:53,233 container.py:100        INFO  Removing container '388e980217285518cc9d85475ee0d7b9dcd4e8a9983386e7a5adf8a44f32ffa0', 1 try...
2024-01-24 00:44:53,258 container.py:103        INFO  Container '388e980217285518cc9d85475ee0d7b9dcd4e8a9983386e7a5adf8a44f32ffa0' removed

.
.
.
11 features passed, 0 failed, 1 skipped
42 scenarios passed, 0 failed, 23 skipped
115 steps passed, 0 failed, 73 skipped, 0 undefined
Took 57m24.484s
2024-01-24 00:48:08,307 cli.py:503        INFO  Finished!
```

At present I have no clue why is it not picked in GHA.

**Comment by jmtd** [comment]
The modules `modules/jre/*` need a module dependency adding like this, the same as the jdk modules:

      - name: jboss.container.openjdk

that's why those tests are not collected for the runtime images.

**Comment by jhuttana** [comment]
> The modules `modules/jre/*` need a module dependency adding like this, the same as the jdk modules:
> 
> ```
>   - name: jboss.container.openjdk
> ```
> 
> that's why those tests are not collected for the runtime images.

Ahhh okay! 
I will make that change :)
There was no clue that it's failing because of that. Curious to know how did you figure it out?

**Review by jmtd — APPROVED** [review]

**Pull request merged**
