### PR TITLE
Add semeru open modules

### PR DESCRIPTION
**Pull request by jerboaa**
Use them for OpenJ9 builds

### CODE REVIEW

**Comment by levivic** [comment]
hi @jerboaa, @mdrafiur on my team is on PTO, you can assign it to me as reviewer instead if you want.

**Comment by jerboaa** [comment]
@levivic sure. I've removed the explicit reviewer. For some reason I cannot add you, but I think you can just review it anyway.

**Comment by levivic** [comment]
@jerboaa this looks good to me. Thx!

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
